fix: add recaptcha form validation check
passioneight/pimcore-google-recaptcha pull request #7
Opened 2022-08-29 03:02 UTC by fmedv

Uses [checkValidity()](https://caniuse.com/form-validation) function to implement simple [form validation check](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity) to prevent form submission if form is invalid.

closes #6

2022-09-02 14:06 UTC, passioneight commented
@fmedv thanks for the contribution! Very much appreciated.
I'll test it over the weekend and get back to you soon :-)

2022-09-02 16:23 UTC, fmedv commented
@passioneight sure thing! It's only two lines of code I've added

Thank you for that awesome repo ;)

2022-09-04 05:50 UTC, passioneight commented
@fmedv here's my two cents: 

I agree that we should consider the `required` attribute of any fields to avoid submitting invalid forms. However, using `checkValidity` will not display any hints to the user as the browser normally would:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/57256630/188298797-e74f59ef-7d0f-4436-91d6-1399ef890fe9.png">

So, I think we should go for the `reportValidity` instead. [Here's an example](https://codepen.io/chriscoyier/pen/mOzgBZ). Though, if we do, we also need to consider the [`novalidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate) attribute of the form itself. Because we'd hinder form submission if the validation was explicitly disabled (e.g., when using tools like [Parsley JS](https://parsleyjs.org/doc/examples/simple.html)).

What do you think? :-)

2022-09-04 05:52 UTC, passioneight requested changes

2022-09-04 05:52 UTC, passioneight commented on src/Resources/public/js/recaptcha.js
> +                            if (form.checkValidity()) {
if (form.noValidate || form.reportValidity()) {

2022-09-07 13:22 UTC, fmedv commented
Sounds perfect. Thanks for your feedback!

2022-09-07 13:24 UTC, fmedv reviewed
Perfect

2022-09-11 05:07 UTC, passioneight approved these changes

2022-09-11 05:07 UTC, merged

2022-09-11 05:08 UTC, passioneight commented
Thanks, @fmedv  :-)